### ISSUE TITLE
Better docs needed. 

### ISSUE THREAD

**Issue by AndreiMotinga** [michelson/dante2#108]
Trying to use it with react, really can't figure this out. 
It looks amazing but been struggling with it for the past hour. 

What is the minimum required to have editor available? 
What is minimum config? 
Who do I supply empty content?
etc.

**Comment by michelson** [comment]
etc ? please try to be more clear in order to get a clear answer.
check the readme were it points to dante-tests repo in which demonstrate a complete react integration.

**Comment by AndreiMotinga** [comment]
Hey @michelson, 

I guess the root of my trouble came from the fact that 5 hours ago I didn't know about draft-js and how it works. I expected regular WYSIWYG, where I'd plug it in and have some html in the end.

Now that I have played [with other editor](https://jpuri.github.io/react-draft-wysiwyg/#/docs), I guess I understand now what dante2 does. 

That being said, I find it very difficult to start with dante. I would expect editor just work with defaults, without the need to provide default config, I'm not sure whether that's the case. 

All in all, a doc page similar to one I referenced above I think would be very helpful. 

In any case, thank you for the work and for this package. I'm pretty sure I'll be using it a bit later. 

Feel free to close this.

**Comment by Bouncey** [comment]
@michelson I guess @AndreiMotinga was looking for a how to. I myself have searched closed issues for hints. 

I have never used Draftjs or Dante, so I have no idea what is required to get this working. There is talk of urls in the config, but what sort of API do they need to hit? Do they expect a response?

The only reason I am sticking with this is because a client has specified the use of Dante2.
