### ISSUE TITLE
which one is better ?

### ISSUE THREAD

**Issue by dsslimshaddy** [michelson/dante2#13]
Which one is better this one or github.com/yabwe/medium-editor/ ?

**Comment by michelson** [comment]
Hi @dsslimshaddy. Well, you will have to do your own math here to make a decision. I think medium-editor is a very complete solution. but has nothing that dante2 already does, maybe it has more configurable options :dagger: 

### some strong points on medium-editor:

+ It has no dependences, so is a light library
+ Clean and well documented
+ Has been adopted by many people, so you have community plugins

### some cons on medium-editor:

+ It's not really a medium editor it just differs a lot of what medium editor is
+ The base library has not all the features of medium so you will have to use community plugins to get close to what medium really does (that's why i've decided to build dante1)
+ It has a poor history handler
+ [It handles DOM instead of data ](https://github.com/yabwe/medium-editor/issues/434)

I think that the fact Medium-editor handles DOM instead of an abstraction of it's data is the most important factor to make a decision, because at least how the editor looks and behaves are fixable things, but here is the thing:

If your editor handles DOM, and all you ingest in your database is DOM you will get into trouble very soon. If you want to update the structural HTML of your _users posts_ you will have to `parse->modify->save` each article in your database. If you got hundreds or thousands articles in your database this will be a pain in the ass.
This is a problem I've faced with Dante-1 and is a no-go for me, that's why I've chosen Draft-js to build Dante-2. 
With Draft-js you save data, no html elements, so you could update how the article looks without touching/parsing/saving the database. You only adjust the components that will display the content and voilá. 
Draft-js provides a `EditorState` structure which is a representation model of your content , instead of handle DOM. So at a text selection/range you operate from DraftJs API, not DOM. Also this `EditorState` provides a transparent history, so undo/redo and multiple versions just works, for free.

An last but no least, when you build a plugin on Dante-2 you work with React-Js which is awesome.

the ball is in your court now, do you shopping and tell us what you think.

happy '17

**Comment by dsslimshaddy** [comment]
I think Dante2 is much better
