### ISSUE TITLE
How do I show the content using editor.emitSerializedOutput()?

### ISSUE THREAD

**Issue by KumarAbhirup** [michelson/dante2#155]
Hi, this is a newbie question.
I see that Draft.js has something like `convertToRaw` for display methods. Another usable thing for Draft.js is [draft-js-utils](https://github.com/sstur/draft-js-utils) which help to render the content on page using HTML.

Can I use those libraries on the data provided by `editor.emitSerializedOutput()` through `onChange` method?

Can you please give a good guide for me about how to implement the JSON response that editor provides?

Makers of Dante.js are awesome 😍

**Comment by michelson** [comment]
Hi @KumarAbhirup , you can use the dante sass styles, search for "styles/dante.scss" in the library code. note that you have to implement all the class names for elements in order for this to work.

I would suggest that you just render the editor in readOnly mode for it to work seamless. 
my approach to make this SEO friendly is to keep metatags and og tags set up in the page from server. I Also use prerender (installed version) in order to catch the search bot requests and give them a server side rendered version of your js.

hope it helps

best
