### ISSUE TITLE
Read only version

### ISSUE THREAD

**Issue by ChristopherParo** [michelson/dante2#172]
Love this project and we're seriously considering using it in our product so thank you!

A question I had was that we are wanting to implement a read only version of Dante2 to try to keep bundle size down to a minimum in the project that consumes the json to display.

Is this something you have considered?

If not how hard would it be to strip that out myself?

**Comment by michelson** [comment]
Hi @ChristopherParo , thanks.

yes you could use something like https://github.com/lokiuz/redraft in order to build a renderer from your serialized content. 

that's the library I use for that too.

the other thing you can do is to save an html version of your content and display that. But I would recommend the Renderer version

best!

**Comment by ChristopherParo** [comment]
Would the read only consider components as well?

**Comment by ChristopherParo** [comment]
@michelson my only concern is that the serialized content doesn't contain the full component logic. Is there a way to maybe export html but instead of the component html I could simply get the component tags.

ie. `"<span><Component /><span>"`

Then I could use a library like https://github.com/TroyAlford/react-jsx-parser to then parse out the components.

**Comment by michelson** [comment]
no @ChristopherParo, serialized content does not contain logic, it only contains data. With [redraft](https://github.com/lokiuz/redraft) you can build a presentation renderer from that data for read only , rendering html string or react components.
