### ISSUE TITLE
What exactly is hapening on Image Upload ?

### ISSUE THREAD

**Issue by dsslimshaddy** [michelson/dante2#20]
When im uploading a picture what is the thing should i return from server ? the uploaded url what format ?

**Comment by michelson** [comment]
when you upload an image to the server , the server should return the url in order to Dante replace the image preview with the uploaded url, this url could be a local image or a remote image if you are using some cdn to store ir like amazon s3.
the format for the server response has to be in json containing a `url` key with the image url , like this
`{url: "http://the-path-to-your-image.jpg"}`

**Comment by dsslimshaddy** [comment]
thanks exactly what i needed
