### ISSUE TITLE
How to render the editor_content in html page?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#37]
Currently, editor is sending editor_content and text_content on store url, after saving the json i.e. editor_content in backend. How to render it on another html page to show the article to the user?
According to the docs, what am I able to know is we can render in editor using window.PocData but there is nothing in docs how to render it in another html page. Thanks in advance for your help.

**Comment by michelson** [comment]
It depends on how you want to display the data. That's because editor sends `editor_content` and `text_content` , with `text_content` you can render the text right away. if you save the content to database just render the text fields were you save the `text_content`
with `editor_content` as you will note is a json structure that represents the content for editor, if you want to display the post as a Dante post, you will have to initialise the editor with `editable` property as `false`

**Comment by sheeshmohsin** [comment]
Thanks for the update.
