### ISSUE TITLE
Function call to explicitly initiate storing editor content to url?

### ISSUE THREAD

**Issue by bbaughn** [michelson/dante2#4]
I would love to know about, or to suggest, a function that could be called in order to immediately send the editor content data to the url endpoint stored with the Dante object.

The regularly timed storing works well unless the user quickly navigates away from the page.  In that case the user may return to the document later and find that not all of their changes have been saved.  If the user can initiate saving themselves before navigating away they can be assured the document will be up to date when they return to it.

**Comment by michelson** [comment]
Hi @bbaughn  , thanks for report this. In fact there is no way to access the editor internal functions. 
I've pushed to master a change that provides that. The instance of the editor component will be available on the main Editor instance in order to access all the internal methods.

let's say you have this implementation:
```
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', function(){
        window.main_editor = new Dante(
          {
            api_key: "mykey",
            el: "app",
            data_storage: {
              url: "http://localhost:3333/store.json"
            }
          }
        )
        editor.render()
      })
    </script>
```

now you can access editor functions like this

`main_editor.editor`

in order to call the save function you have to do this:

`main_editor.editor.dispatchChangesToSave()`

note that this function will check on editor changes in order to submit the data to server.

please tell us if this works for you. right now this change is only in master branch

best

**Comment by michelson** [comment]
cool! we be included in the next release
