### ISSUE TITLE
How to use it in my site

### ISSUE THREAD

**Issue by philgyford** [michelson/dante2#66]
Dante2 looks great but I can't work out how to use it in my existing Node site. I'm far from a Node expert (I'm much more familiar with Python and PHP).

I've installed the module, but now what? You have an example of how to initialise it:

```
new Dante({   
  upload_url: "http://localhost:9292/uploads/new",    
  store_url: "http://localhost:3333/store.json",    
  el: "app"  
 })
```

And I'm guessing I need to have an element like this in my page:

    <div id="app"></div>

And will need to have something (what?) happen when requests are made to those two URLs.

But obviously I also need to include some Dante2 JS and CSS files somewhere, somehow. Are there instructions for what else I need to do?

Sorry if I sound stupid - I don't see anyone else here having this problem - but I'm baffled!

**Comment by philgyford** [comment]
Thanks. I'm not using a preprocessor - I have a directory of JS files (which will probably get minified and combined later) and I'm using Sass to compile the CSS files.

**Comment by jaroslawziolkowski** [comment]
@michelson I get https://github.com/michelson/dante2-tests and try run `yarn install yarn run`
and this is full of errors

<img width="1345" alt="zrzut ekranu 2017-07-28 o 14 11 41" src="https://user-images.githubusercontent.com/6404533/28716678-c8252f9c-739e-11e7-8bb0-7c555bb83af3.png">

this is the same problem like import Editor to ES6 in own project.

**Comment by michelson** [comment]
Hi , I've tested again the repo and is working fine.

try this: `yarn upgrade Dante2` then `yarn start`

![image](https://user-images.githubusercontent.com/11976/28720505-5c80c0f8-737b-11e7-83da-9210801f4bd3.png)

**Comment by jaroslawziolkowski** [comment]
@michelson still the same errors. BTW yarn display warnings because https://github.com/michelson/dante2-tests/blob/master/package.json in dev and dependencies is different version for babel-core and babel-loader
sass-loader need to node-sass and extract-text-webpack-plugin plugin doesn't exists in version 2.0.0-beta but 2.0.0-beta.1 - 2.0.0-beta.5 or higher

After delete this warning still I see problems. And when I see code this is logic.

All my log

<img width="1731" alt="zrzut ekranu 2017-07-28 o 21 03 36" src="https://user-images.githubusercontent.com/6404533/28732543-8251eafc-73d8-11e7-9cbd-b542d9e46e81.png">
<img width="879" alt="zrzut ekranu 2017-07-28 o 21 04 15" src="https://user-images.githubusercontent.com/6404533/28732544-82584eb0-73d8-11e7-9164-8b10eea63f18.png">
<img width="1815" alt="zrzut ekranu 2017-07-28 o 21 04 40" src="https://user-images.githubusercontent.com/6404533/28732547-825ed87a-73d8-11e7-97c5-d9c05731643b.png">
<img width="1660" alt="zrzut ekranu 2017-07-28 o 21 05 13" src="https://user-images.githubusercontent.com/6404533/28732545-825bd4e0-73d8-11e7-8562-752bb9c4ab07.png">

**Comment by THook** [comment]
Can't run dante2-tests either, even after yarn upgrading Dante2. Error coming from extract-text-webpack-plugin it seems... Any thought?

**Comment by michelson** [comment]
dante2-tests updated with latest version of dante2, 0.4.0 and is working as expected now
ps: if you use dante-test with a development version of Dante2 (aka: from github) you will need to run the build command on the node_module, so: `cd ./node_modules/Dante2` & `yarn build`

please reopen this issue if you get something wrong
