### ISSUE TITLE
How can I turn off the tooltip popup on links?

### ISSUE THREAD

**Issue by Bodacious** [michelson/dante2#69]
This is an annoying and unnecessary feature. Is there any quick and simple way for me to disable it completely?

**Comment by michelson** [comment]
Yes , check out Dante tests in order to see how to customize the
configuration

Best


El 26 ago. 2017 9:32 AM, "Gavin Morrice" <notifications@github.com>
escribió:

This is an annoying and unnecessary feature. Is there any quick and simple
way for me to disable it completely?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/michelson/dante2/issues/69>, or mute the thread

**Comment by Bodacious** [comment]
Where are the test files?

**Comment by michelson** [comment]
Sorry, is another repo https://github.com/michelson/dante2-tests

El 26 ago. 2017 2:12 PM, "Gavin Morrice" <notifications@github.com>
escribió:

Where are the test files?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/michelson/dante2/issues/69#issuecomment-325148008>, or mute
the thread
