### ISSUE TITLE
data_storage json string to function rather than to url

### ISSUE THREAD

**Issue by vephinx** [michelson/dante2#7]
Would it be, or is it possible, to send the editor content json string from to a function rather than posting it to a URL?

Thanks!

**Comment by michelson** [comment]
Hi @vephinx , 
what would be the use case for that need ?
maybe you can accomplish that using the callbacks around the store function, like
```
      xhr: before_handler() 
      data_storage: success_handler(result)
      xhr: success_handler(result)
      xhr: failure_handler(error)
```

regards

**Comment by vephinx** [comment]
@michelson I'm using [Meteor](https://meteor.com) and I would like to set the content to a document my collection and let Meteor handle passing it to the server.

**Comment by michelson** [comment]
@vephinx what you mean by `set the content to a document in my collection`  ?
why you don't let the server handle that ?

**Comment by vephinx** [comment]
So on the client I subscribe to a collection called `notes`. I would like to call the function `saveContent` (see below), instead of calling a URL. This automatically pushes the changes to the server using Meteor magic.

```
saveContent = function(json) {
  note = notes.findOne({ _id: noteId});
  note.content = json;
};
```

**Comment by michelson** [comment]
sorry , I don't use meteor so don't know which is the magic it does.
in Meteor is possible to update the `note` on memory ? without touch the server?, let's say when D2 hits the server it will return the contents and then you could update the model, using the callbacks so you could keep the model in sync.

Anyway you could check the [save_content.coffee](https://github.com/michelson/dante2/blob/master/app/utils/save_content.coffee) and see how it works maybe it could be a good idea to make this configurable in order to use another solution or extend the same class.

**Comment by vephinx** [comment]
@michelson I made these changes to [save_content.coffee]() 
Line 15 I commented out:
```coffeescript
# return unless @config.data_storage.url
```

And on line 47 I added:
```coffeescript
@config.data_storage.save_handler(JSON.stringify(content)) if @config.data_storage.save_handler
return unless @config.data_storage.url
```

Now I can do:
```javascript
          data_storage: {
            interval: 1500,
            save_handler: saveContent
          }
```

**Comment by michelson** [comment]
Hi @vephinx, cool! that should be enough to make it work , are you going to make a PR for this ? if not I could update the source un the next days in order to close this issue

happy holidays!

**Comment by michelson** [comment]
hi @vephinx , version 0.3.2 implements the save_handler in data_storage to override the ajax

cheers
