### ISSUE TITLE
HOWTO upgrade dante to dante2

### ISSUE THREAD

**Issue by netpenthe** [michelson/dante2#77]
Are there any instructions? Is it a drop in replacement?

Thanks in advance :)

**Comment by michelson** [comment]
Hi @netpenthe , no it's not a drop in replacement, the D2 API is almost identical to D1 API, but they are not the same, you have to do little tweaks to your code, not a thing to worry about . 
The other thing you will note is the stored content, in Dante1 it's a html text, but in Dante2 is a json structure provided by draft, so that's the hard part because you will need to convert the html to draft contentState. 
hint: use https://github.com/HubSpot/draft-convert to translate serialize the html to contentState
